name: CI
on:
- push
- pull_request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis
        ports:
        - "5432:5432"
        env:
          POSTGRES_USER: fluentpostgis
          POSTGRES_PASSWORD: fluentpostgis
          POSTGRES_DB: postgis_tests
    steps:
    - uses: actions/checkout@v3
    - run: swift test --enable-test-discovery
